/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AFuncCall extends PFuncCall
{
    private TId _id_;
    private final LinkedList _expression_ = new TypedLinkedList(new Expression_Cast());

    public AFuncCall()
    {
    }

    public AFuncCall(
        TId _id_,
        List _expression_)
    {
        setId(_id_);

        {
            this._expression_.clear();
            this._expression_.addAll(_expression_);
        }

    }
    public Object clone()
    {
        return new AFuncCall(
            (TId) cloneNode(_id_),
            cloneList(_expression_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFuncCall(this);
    }

    public TId getId()
    {
        return _id_;
    }

    public void setId(TId node)
    {
        if(_id_ != null)
        {
            _id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _id_ = node;
    }

    public LinkedList getExpression()
    {
        return _expression_;
    }

    public void setExpression(List list)
    {
        _expression_.clear();
        _expression_.addAll(list);
    }

    public String toString()
    {
        return ""
            + toString(_id_)
            + toString(_expression_);
    }

    void removeChild(Node child)
    {
        if(_id_ == child)
        {
            _id_ = null;
            return;
        }

        if(_expression_.remove(child))
        {
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        for(ListIterator i = _expression_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

    }

    private class Expression_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PExpression node = (PExpression) o;

            if((node.parent() != null) &&
                (node.parent() != AFuncCall.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != AFuncCall.this))
            {
                node.parent(AFuncCall.this);
            }

            return node;
        }
    }
}
