/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class ANotFirstImportId extends PNotFirstImportId
{
    private TId _id_;
    private final LinkedList _importAlias_ = new TypedLinkedList(new ImportAlias_Cast());

    public ANotFirstImportId()
    {
    }

    public ANotFirstImportId(
        TId _id_,
        List _importAlias_)
    {
        setId(_id_);

        {
            this._importAlias_.clear();
            this._importAlias_.addAll(_importAlias_);
        }

    }
    public Object clone()
    {
        return new ANotFirstImportId(
            (TId) cloneNode(_id_),
            cloneList(_importAlias_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANotFirstImportId(this);
    }

    public TId getId()
    {
        return _id_;
    }

    public void setId(TId node)
    {
        if(_id_ != null)
        {
            _id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _id_ = node;
    }

    public LinkedList getImportAlias()
    {
        return _importAlias_;
    }

    public void setImportAlias(List list)
    {
        _importAlias_.clear();
        _importAlias_.addAll(list);
    }

    public String toString()
    {
        return ""
            + toString(_id_)
            + toString(_importAlias_);
    }

    void removeChild(Node child)
    {
        if(_id_ == child)
        {
            _id_ = null;
            return;
        }

        if(_importAlias_.remove(child))
        {
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        for(ListIterator i = _importAlias_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

    }

    private class ImportAlias_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PImportAlias node = (PImportAlias) o;

            if((node.parent() != null) &&
                (node.parent() != ANotFirstImportId.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != ANotFirstImportId.this))
            {
                node.parent(ANotFirstImportId.this);
            }

            return node;
        }
    }
}
