/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AWithoutFromImportRule extends PImportRule
{
    private PModule _module_;
    private final LinkedList _importAlias_ = new TypedLinkedList(new ImportAlias_Cast());
    private final LinkedList _notFirstImportModule_ = new TypedLinkedList(new NotFirstImportModule_Cast());

    public AWithoutFromImportRule()
    {
    }

    public AWithoutFromImportRule(
        PModule _module_,
        List _importAlias_,
        List _notFirstImportModule_)
    {
        setModule(_module_);

        {
            this._importAlias_.clear();
            this._importAlias_.addAll(_importAlias_);
        }

        {
            this._notFirstImportModule_.clear();
            this._notFirstImportModule_.addAll(_notFirstImportModule_);
        }

    }
    public Object clone()
    {
        return new AWithoutFromImportRule(
            (PModule) cloneNode(_module_),
            cloneList(_importAlias_),
            cloneList(_notFirstImportModule_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAWithoutFromImportRule(this);
    }

    public PModule getModule()
    {
        return _module_;
    }

    public void setModule(PModule node)
    {
        if(_module_ != null)
        {
            _module_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _module_ = node;
    }

    public LinkedList getImportAlias()
    {
        return _importAlias_;
    }

    public void setImportAlias(List list)
    {
        _importAlias_.clear();
        _importAlias_.addAll(list);
    }

    public LinkedList getNotFirstImportModule()
    {
        return _notFirstImportModule_;
    }

    public void setNotFirstImportModule(List list)
    {
        _notFirstImportModule_.clear();
        _notFirstImportModule_.addAll(list);
    }

    public String toString()
    {
        return ""
            + toString(_module_)
            + toString(_importAlias_)
            + toString(_notFirstImportModule_);
    }

    void removeChild(Node child)
    {
        if(_module_ == child)
        {
            _module_ = null;
            return;
        }

        if(_importAlias_.remove(child))
        {
            return;
        }

        if(_notFirstImportModule_.remove(child))
        {
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_module_ == oldChild)
        {
            setModule((PModule) newChild);
            return;
        }

        for(ListIterator i = _importAlias_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        for(ListIterator i = _notFirstImportModule_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

    }

    private class ImportAlias_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PImportAlias node = (PImportAlias) o;

            if((node.parent() != null) &&
                (node.parent() != AWithoutFromImportRule.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != AWithoutFromImportRule.this))
            {
                node.parent(AWithoutFromImportRule.this);
            }

            return node;
        }
    }

    private class NotFirstImportModule_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PNotFirstImportModule node = (PNotFirstImportModule) o;

            if((node.parent() != null) &&
                (node.parent() != AWithoutFromImportRule.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != AWithoutFromImportRule.this))
            {
                node.parent(AWithoutFromImportRule.this);
            }

            return node;
        }
    }
}
