/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AWithFromImportRule extends PImportRule
{
    private PModule _module_;
    private TId _id_;
    private final LinkedList _importAlias_ = new TypedLinkedList(new ImportAlias_Cast());
    private final LinkedList _notFirstImportId_ = new TypedLinkedList(new NotFirstImportId_Cast());

    public AWithFromImportRule()
    {
    }

    public AWithFromImportRule(
        PModule _module_,
        TId _id_,
        List _importAlias_,
        List _notFirstImportId_)
    {
        setModule(_module_);

        setId(_id_);

        {
            this._importAlias_.clear();
            this._importAlias_.addAll(_importAlias_);
        }

        {
            this._notFirstImportId_.clear();
            this._notFirstImportId_.addAll(_notFirstImportId_);
        }

    }
    public Object clone()
    {
        return new AWithFromImportRule(
            (PModule) cloneNode(_module_),
            (TId) cloneNode(_id_),
            cloneList(_importAlias_),
            cloneList(_notFirstImportId_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAWithFromImportRule(this);
    }

    public PModule getModule()
    {
        return _module_;
    }

    public void setModule(PModule node)
    {
        if(_module_ != null)
        {
            _module_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _module_ = node;
    }

    public TId getId()
    {
        return _id_;
    }

    public void setId(TId node)
    {
        if(_id_ != null)
        {
            _id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _id_ = node;
    }

    public LinkedList getImportAlias()
    {
        return _importAlias_;
    }

    public void setImportAlias(List list)
    {
        _importAlias_.clear();
        _importAlias_.addAll(list);
    }

    public LinkedList getNotFirstImportId()
    {
        return _notFirstImportId_;
    }

    public void setNotFirstImportId(List list)
    {
        _notFirstImportId_.clear();
        _notFirstImportId_.addAll(list);
    }

    public String toString()
    {
        return ""
            + toString(_module_)
            + toString(_id_)
            + toString(_importAlias_)
            + toString(_notFirstImportId_);
    }

    void removeChild(Node child)
    {
        if(_module_ == child)
        {
            _module_ = null;
            return;
        }

        if(_id_ == child)
        {
            _id_ = null;
            return;
        }

        if(_importAlias_.remove(child))
        {
            return;
        }

        if(_notFirstImportId_.remove(child))
        {
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_module_ == oldChild)
        {
            setModule((PModule) newChild);
            return;
        }

        if(_id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        for(ListIterator i = _importAlias_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        for(ListIterator i = _notFirstImportId_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

    }

    private class ImportAlias_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PImportAlias node = (PImportAlias) o;

            if((node.parent() != null) &&
                (node.parent() != AWithFromImportRule.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != AWithFromImportRule.this))
            {
                node.parent(AWithFromImportRule.this);
            }

            return node;
        }
    }

    private class NotFirstImportId_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PNotFirstImportId node = (PNotFirstImportId) o;

            if((node.parent() != null) &&
                (node.parent() != AWithFromImportRule.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != AWithFromImportRule.this))
            {
                node.parent(AWithFromImportRule.this);
            }

            return node;
        }
    }
}
