/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import minipython.analysis.*;

public final class TAs extends Token
{
    public TAs()
    {
        super.setText("as");
    }

    public TAs(int line, int pos)
    {
        super.setText("as");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TAs(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTAs(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TAs text.");
    }
}
