/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import minipython.analysis.*;

public final class TElif extends Token
{
    public TElif()
    {
        super.setText("elif");
    }

    public TElif(int line, int pos)
    {
        super.setText("elif");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TElif(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTElif(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TElif text.");
    }
}
