/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import minipython.analysis.*;

public final class TGreatEq extends Token
{
    public TGreatEq()
    {
        super.setText(">=");
    }

    public TGreatEq(int line, int pos)
    {
        super.setText(">=");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TGreatEq(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTGreatEq(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TGreatEq text.");
    }
}
