/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import minipython.analysis.*;

public final class TGreat extends Token
{
    public TGreat()
    {
        super.setText(">");
    }

    public TGreat(int line, int pos)
    {
        super.setText(">");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TGreat(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTGreat(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TGreat text.");
    }
}
