/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import minipython.analysis.*;

public final class TLessEq extends Token
{
    public TLessEq()
    {
        super.setText("<=");
    }

    public TLessEq(int line, int pos)
    {
        super.setText("<=");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TLessEq(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTLessEq(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TLessEq text.");
    }
}
