/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import minipython.analysis.*;

public final class TLess extends Token
{
    public TLess()
    {
        super.setText("<");
    }

    public TLess(int line, int pos)
    {
        super.setText("<");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TLess(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTLess(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TLess text.");
    }
}
