/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import minipython.analysis.*;

public final class TMin extends Token
{
    public TMin()
    {
        super.setText("min");
    }

    public TMin(int line, int pos)
    {
        super.setText("min");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TMin(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTMin(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TMin text.");
    }
}
