/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import minipython.analysis.*;

public final class TNone extends Token
{
    public TNone()
    {
        super.setText("None");
    }

    public TNone(int line, int pos)
    {
        super.setText("None");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TNone(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTNone(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TNone text.");
    }
}
