/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import minipython.analysis.*;

public final class TNotEq extends Token
{
    public TNotEq()
    {
        super.setText("!=");
    }

    public TNotEq(int line, int pos)
    {
        super.setText("!=");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TNotEq(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTNotEq(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TNotEq text.");
    }
}
