/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import minipython.analysis.*;

public final class TSep extends Token
{
    public TSep()
    {
        super.setText(".");
    }

    public TSep(int line, int pos)
    {
        super.setText(".");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TSep(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTSep(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TSep text.");
    }
}
